spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  thymeleaf:
    view-names: thymeleaf/*
  datasource:
    url: jdbc:postgresql://ec2-34-251-115-141.eu-west-1.compute.amazonaws.com:5432/d7ad7vnr5q80ub
    username: dbuwrqojiynhbi
    password: 2736c4e71d761f67e18baf0e5cdfcb24581253667886b1bad9918f1e3442414b
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 266838271022-rvslt803ato8fs5gihu8mr10l5saj740.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

server:
  error:
    path: /error